services:
  - type: web
    name: workout-tracker-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://workout-tracker-app.windsurf.build
      - key: NODE_ENV
        value: production
